### ISSUE TITLE
web footer icon 

### ISSUE THREAD

**Issue by captain-sensible** [bcit-ci/ci-design#10]
Other PHP frameworks have web page footer icons so you can display the fact that you are using the PHP framework. The CI guys tell me mine is "Tacky" : 
https://twitter.com/andybrookestar/status/851158749750464512

&  i can get one here - can't see any png, gif nor jpg in download zip of repo.

**Comment by jim-parry** [comment]
Not so much that your icon is tacky, but ising a grunge font and abbreviating CodeIgniter to "C.I" is tacky.
The website/assets/images folder contains a number of gif & png renderings of the logo, and the media/ci-logo folder contains an Illustrator format original.
